### ISSUE TITLE
Complete the TCK user documentation

### ISSUE THREAD

**Issue by wes-johnson** [eclipse-sparkplug/sparkplug#169]
This could be mostly incorporated into the web console, so that the separate "Getting started" could be quite short.  We'll see.

**Comment by icraggs-sparkplug** [comment]
User Guide outlining

Software requirements
Installation and configuration
How to run the tests
Where to file challenges
TCK specific rules not covered in this process guide

Instructions describing how to run the compatible implementation(s) that are being used to validate the TCK

A top-level README document pointing to each of the preceding documents

We recommend that the TCK documentation include

URLs for the issue trackers to file certification requests, bug reports, etc.

A statement that the Certification of Compatibility process must be followed before a claim of compatibility can be made.

TCK binaries MAY contain

Test coverage document
Test assertion document

**Comment by icraggs-sparkplug** [comment]
This is done.
