### ISSUE TITLE
Update the TCK license per the posted Eclipse license

### ISSUE THREAD

**Issue by wes-johnson** [eclipse-sparkplug/sparkplug#329]
See here: https://www.eclipse.org/legal/tck.php

**Comment by icraggs-sparkplug** [comment]
"The code in the repo should reference the EPL. The zip file for the "binary" TCK offered for download should contain the TCK license (and only the TCK license)." From Frédéric.

**Comment by icraggs-sparkplug** [comment]
That's done in the packaging script.
