### ISSUE TITLE
Couple of questions on how tot use TCK

### ISSUE THREAD

**Issue by cosminbauer** [eclipse-sparkplug/sparkplug#386]
Hello Gents,

I am trying to use the test app and run the Edge Node tests on a system that I am building. My setup is a Edge device running a containerized SparkplugB module which is reading live data from an RTU(device), connected to an MQTT Server and on the server I also have Ignition subscribed so it can receive the data I am pushing. 
So, I have connected both my EdgeNode(Edge device running SparkplugB) and Ignition to HiveMQ. Setup the appropiate  group_id / edge_node_id and device Id and followed the instructions as follows : 

1. Setup a MQTT Connection to the HiveMQ Sparkplug test server.
2. Set a Group, Edge and Device Ids to be checked.
3. Start this test.
4. Terminate the edge node and device named. 

At this point my EdgeNode was running already and publishing messages. Started with NBIRTH, DBIRTH and followed by DDATA , I had a continous logic that is pushing data from the device.
As it was running for a while, I have stopped it  at this point.

5. Wait until Tests are finished and check Results

Left the test running overnight and it never stopped and published any logs. I have stopped it manually the next day and now trying to understand the content, 

If could help me please identify what I might be doing wrong while setting it up, or things that I might ajust.
Also NOT EXECUTED for a test does it mean it could not do it because it did not had the proper conditions or could there be other reasons ?

I have attached the log aswell.

Thanks,
Cosmin

[SparkplugTCKresults.txt](https://github.com/eclipse/sparkplug/files/9936924/SparkplugTCKresults.txt)

**Comment by icraggs-sparkplug** [comment]
Hi. We're in the process of updating the TCK and the specification in preparation for the first release. There are many updates, and (hopefully) better instructions. A release candidate was created a few days ago: 

https://github.com/eclipse/sparkplug/releases/tag/v3.0.0-rc1

The specification has also changed in parts, especially in the area of Host Application state messages which means that the existing Ignition implementations will not pass all the tests. With the new TCK release, however, you can use a simulated host application to test the edge node. 

Please try the updated TCK and let us know if that works better for you.

**Comment by Llorx** [comment]
Hi @icraggs-sparkplug . I see that the website says that [the release date was the 16 november](https://projects.eclipse.org/projects/iot.sparkplug/releases/3.0.0) and it shows some info, but the [download section has no release](https://projects.eclipse.org/projects/iot.sparkplug/downloads) and here on GitHub the latest release is srill the rc1.

Is there something I'm missing to search?

**Comment by cosminbauer** [comment]
> Hi. We're in the process of updating the TCK and the specification in preparation for the first release. There are many updates, and (hopefully) better instructions. A release candidate was created a few days ago:
> 
> https://github.com/eclipse/sparkplug/releases/tag/v3.0.0-rc1
> 
> The specification has also changed in parts, especially in the area of Host Application state messages which means that the existing Ignition implementations will not pass all the tests. With the new TCK release, however, you can use a simulated host application to test the edge node.
> 
> Please try the updated TCK and let us know if that works better for you.

Thanks for you reply. I have taken this version and used it but with the same results. Followed the steps in the Edge Node section the Session Establishment Test with the same result as the ones attached above. 

1. Connect this console to the HiveMQ broker.
2. Set the Host App, Group, Edge Node and Device ids.
3. Ensure the Host App is started, if you are using a real one.

I have tried using Ignition(SCADA) and also tried to simulate an ONLINE status if as an Host App was connected but with no luck.

4. Start this test.
5. Connect the Edge Node and Device.

At this stage I have started my containers running SparkplugB an started publshing NBIRTH, DBIRTH and then DDATA for all the metrics I have.
      
7. Wait until the test is finished and check the results.

Waited for more then 24h and with no success. Tried to leave it running for 2-3 hrs with the same results.

9. If the test does not stop automatically, press the "Stop Test" button.

Let me explain how I undersntand this app in the context of the Edge Node tests. We have our end-to-end Edge - SCADA system ready for testing. On the TCK app start HIVEMQ and connect. Setup the GROUP, NODE and DEVICE IDS, as I have them configured on my Edge system(device), in the same time start the HOST app I understand the HOST as the SCADA app I am using in my case. Start that and it will send a retained ONLINE message on the MQTT server and after all of the above is done start my containers running SparkplugB within my Edge device and let the tests run. 

This is how I understand the system as a hole and the role of the TCK app in my system test. The GOAL for me would be to prove the SparkplugB message order\structure etc I send out of the Edge device pass the TCK tests.

Please let me know and advise If you belive I could do things differently.

Thank you,
Cosmin

**Comment by cosminbauer** [comment]
Also could you please let me know if the "How to" procedure is out ? Thank you, Cosmin

**Comment by wes-johnson** [comment]
@cosminbauer - This User guide is now linked here and the TCK has been released: https://github.com/eclipse-sparkplug/sparkplug/blob/develop/tck/README.md
