### ISSUE TITLE
Assertions without capitalized MUST/MAY/SHOULD 

### ISSUE THREAD

**Issue by icraggs-sparkplug** [eclipse-sparkplug/sparkplug#395]
In writing a program to determine the status of assertions I found these:

- If the Sparkplug Host Application ever disconnects intentionally, it must publish a Death message with the following characteristics.
- When using multiple MQTT Servers and Edge Nodes are configured with a Primary Host Application, the Primary Host Application instance must be configured to publish a STATE Birth Certificate and all Edge Nodes need to subscribe to this STATE message.
- The NBIRTH message must have been sent within the current MQTT session prior to a DBIRTH being published.
- For each metric in the DBIRTH, the value must be set to the current value or if the current value is null, have the is_null flag set to true and no value specified.
- For each metric in the NBIRTH, the value must be set to the current value or if the current value is null, have the is_null flag set to true and no value specified.
- When using multiple MQTT Servers and Edge Nodes are configured with a Primary Host Application, the Primary Host Application instance must be configured to publish a STATE Birth Certificate and all Edge Nodes need to subscribe to this STATE message.

Also this one, where the "can" ought to be a MAY, I think:

- If the missing messages that triggered the start of the Reorder Timeout timer arrive before the reordering timer elapses, the timer can be terminated and normal operation in the Host Application can continue

**Comment by wes-johnson** [comment]
Fixed here: https://github.com/eclipse-sparkplug/sparkplug/commit/350d3470a7ff0173cecfd85fc2a6fa923f6b7c0b
