### ISSUE TITLE
TCK Webconsole Access

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse-sparkplug/sparkplug#399]
I run the Sparkplug TCK in an Ubuntu Server within a virtual machine, in the context of a non-public network.

The web interface is bound to TCP 127.0.0.1:3000. Could this be changed to 0.0.0.0:3000 (the gist being able to access the port externally)?

This would make accessing the web client trivial or accessible without running SSH commands on the remote machine (and having to restart the SSH session should the web client be restarted).

**Comment by icraggs-sparkplug** [comment]
You can change the host and port by adding a server section to nuxt.config.js in the webconsole directory. Docs here: https://nuxtjs.org/docs/features/configuration/#edit-host-and-port

    export default {
     ...
      server: {
         host: 0,       // defaults to localhost
         port: 4500     // if you wanted to change the port too
      }
      ...
    }

Is it enough to document this?
