### ISSUE TITLE
Confused about bdSeq - TCK seems to want something different from spec

### ISSUE THREAD

**Issue by asthomas** [eclipse-sparkplug/sparkplug#425]
### What do you want to know?

I am testing an EoN device using the TCK.  The first three lines of output from the edge node "Session Establishment Test" look like this:
```
Monitor: Test failed for assertion topics-nbirth-bdseq-increment: edge id: PidChildren/PID2
INFO: Actual bdseq: 0 expected bdseq: 1
INFO: Actual bdseq: 0 expected bdseq: 1
```
I guess this is checking the LWT message in the MQTT CONNECT packet.  When I read the spec, I think it says:
* The LWT message in the first CONNECT will have a bdSeq of 0
* All NBIRTH messages emitted after the CONNECT will have a bdSeq of 0
* An explicit NDEATH message emitted prior to a graceful DISCONNECT will have a bdSeq of 0
* The LWT message in the next CONNECT will have a bdSeq of 1
* All NBIRTH messages and an explicit NDEATH will have a bdSeq of 1
* ... and so on

Why does the TCK expect a bdSeq of 1 in this case?  Is there an implication that bdSeq must survive a device reset or power cycle?  That is not consistent with the TCK's output.  I have run this test many times, and the TCK always expects a bdSeq of 1, not an ever-rising value.

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by amine-amaach** [comment]
I'm also having this issue which is probably caused by HiveMQ. I have to restart the broker before running any other test.

**Comment by bryce-nakatani** [comment]
The bdSeq needs to be retained between application/device restarts. Take a
look at the tahu compatible edge implementation. There's an example of
using the filesystem to retain the bdSeq.

**Comment by jvisser-di** [comment]
@bryce-nakatani It would be very helpful for us to know the reasoning behind this. Can you explain the reasoning as why it is done like this? And what fails if you don't? It would help us a lot with some decisions of a application we are designing.

**Comment by bryce-nakatani** [comment]
I'm not aware of the history of the retention.

In reality, the host has to be "flexible" on the next bdSeq. The reality is
that Edge nodes may be physically replaced, firmware updates could
purge/erase this type of retained data, or devices don't have the ability
to retain values and thus a power cycle resets the last known bdSeq.

The TCK will check for sequential bdSeq changes but it doesn't require any
of the "reality" conditions I mentioned earlier.
