### ISSUE TITLE
Question: Spec ambiguities. Aliases, templates and instances?

### ISSUE THREAD

**Issue by Llorx** [eclipse-sparkplug/sparkplug#431]
Hi,

I can't find info about this in the Sparkplug specification.

Having alises enabled, it says that for each metric you should send an alias and that not two metrics should have the same alias. It also says that you have to send the alias and name on each NBIRTH and DBIRTH message.

Now the problem arises when I'm sending Templates and instances of those templates.

It says that I have to send all the metric info in my NBIRTH and DBIRTH messages, so here is the situation:
- I have one template named "INV" that contains one metric named "test".
- I have one device named "DEV01" that contains one metric, which is an instance of INV named "New INV".

With this premise I send these messages:
- NBIRTH message with the Template definition that includes all the metrics:
```json
{
    "timestamp": 1677686913593,
    "seq": 0,
    "metrics": [{
		"name": "bdSeq",
		"timestamp": 1677686913588,
		"value": 0,
		"type": "UInt64"
	}, {
		"name": "Node Control/Rebirth",
		"timestamp": 1677686913588,
		"type": "Boolean",
		"value": false
	}, {
		"name": "Node Control/Next Server",
		"timestamp": 1677686913588,
		"type": "Boolean",
		"value": false
	}, {
		"name": "INV",
		"type": "Template",
		"isDefinition": true,
		"value": {
			"version": "1677686913592",
			"templateRef": "",
			"metrics": [{
				"name": "test",
				"alias": 1,
				"timestamp": 1677686913118,
				"value": 61713,
				"type": "Double",
				"properties": {
					"not_updated_prop": {
						"value": "test",
						"type": "String"
					},
                                        "updated_prop": {
						"value": "test",
						"type": "String"
					}
				}
			}]
		}
	}]
}
```
As you can see, there's a metric named `INV`, which is a Template definition, that includes a metric named `test` with an alias id `1`. Everything fine up here.
- Then I send this DBIRTH message:
```json
{
    "timestamp": 1677686913610,
    "seq": 1,
    "metrics": [{
		"name": "Device Control/Rebirth",
		"timestamp": 1677686913609,
		"type": "Boolean",
		"value": false
	}, {
		"name": "New INV",
		"alias": 3,
		"type": "Template",
		"timestamp": 1677686913609,
		"isDefinition": false,
		"value": {
			"templateRef": "INV",
			"metrics": [{
				"name": "test",
				"alias": 4,
				"timestamp": 1677686913118,
				"value": 61713,
				"type": "Double",
				"properties": {
					"not_updated_prop": {
						"value": "test",
						"type": "String"
					},
                                        "updated_prop": {
						"value": "newtest",
						"type": "String"
					}
				}
			}]
		}
	}]
}
```
And here is the problem. The specification says that I have to send the name along with the alias for each metric when sending a NBIRTH or DBIRTH command, so although I've already sent an alias for the metric `test` inside the `INV` template in the NBIRTH command, I'm also sending an alias along the name `test` in the DBIRTH command, but being an instance of the INV template I'm unsure if I have to define a new alias id (in this case I'm sending a 1 in the definition and a 4 in the instance), because is a new device so inside this device this metric is considered a different one, or I should send the same alias id as the NBIRTH command (sending 1 for both the template and the instance), because in the end is the same alias.

And another problem is if I should even send the metric name, as it has already been sent by the NBIRTH command so I should only send the updated data, for example, not sending the name and not sending the "not_updated_prop" property as the value has not changed, like it is just a DDATA inside the template instance, because this metric definition has already been sent with the NBIRTH command, so is duplicated data.

- [X] I agree to the terms of EFTL

**Comment by wes-johnson** [comment]
So for template definitions there is no reason/point in including an alias. Conceptually, the aliases are used in place of the metric name in DATA messages. Since template definitions only exist in NBIRTH messages, an alias has no significance or use in a template definition. So, you should use aliases in the template instances only. Then you only need to include the aliases for those given template metric members that change in subsequent DATA messages.

**Comment by Llorx** [comment]
Ok, perfect. And metrics of two different instances of the same template should have different alias IDs I guess, right?
