### ISSUE TITLE
Question: [ADD SUMMARY HERE]

### ISSUE THREAD

**Issue by luke-shields** [eclipse-sparkplug/sparkplug#465]
### What do you want to know?

When an Edge node and it's associated devices are going 'offline', should both an NDEATH and DDEATH(s) be published? Or is just the NDEATH sufficient

Thanks!

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by bryce-nakatani** [comment]
An NDEATH (node death) is sufficient. From the perspective of the host
application, when receiving the NDEATH, it will set the node and all
devices of that node offline.
