### ISSUE TITLE
TCK not producing log file

### ISSUE THREAD

**Issue by Mahersrasra** [eclipse-sparkplug/sparkplug#479]
### What happened?

While conducting tests on my MQTT server for Sparkplug certification, I've encountered an issue. Specifically, I've noticed that there are no trace logs present in the HiveMQ bin directory. I'm unsure about the root cause of this problem and would greatly appreciate assistance in resolving it. If anyone could provide guidance on addressing this issue, it would be helpful. 

![image](https://github.com/eclipse-sparkplug/sparkplug/assets/78274224/63aa96d8-1019-4d7b-ba18-35572ed25569)

![image](https://github.com/eclipse-sparkplug/sparkplug/assets/78274224/25e6fe2d-e2f7-4d10-91d9-fefa89b10983)

### What is the product or software this issue was discovered with?

- Hive mq broker 4.18.0

- Sparkplug TCK 3.0.0

### What exact steps need to be performed to reproduce the problem?

in the broker section , try Sparkplug Compliant Test

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by icraggs-sparkplug** [comment]
I presume this is the same issue as #476 - I have put in a reply there.
