### ISSUE TITLE
Question: Where is the TCK extension, *sparkplug-tck-3.0.0.zip*?

### ISSUE THREAD

**Issue by scottmwyant** [eclipse-sparkplug/sparkplug#482]
### What do you want to know?

The User Guide says to copy an "extension distribution file" but it's not clear as to the source where the file is obtained.  Looks like there may be a broken link in the documentation.

> **HiveMQ Broker**
> Install the HiveMQ broker following the instructions provided with it.
> 
> Copy the extension distribution file (tck/build/hivemq-extension/sparkplug-tck-3.0.1-SNAPSHOT.zip) to the HiveMQ extension folder...
> 

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by icraggs-sparkplug** [comment]
The https://sparkplug.eclipse.org/compatibility/get-listed/ web page has a link in the "DOWNLOAD, RUN AND PASS THE TCK" section:

    You can download the current TCK binaries from [here](https://download.eclipse.org/sparkplug/3.0.0/Eclipse-Sparkplug-TCK-3.0.0.zip).

Were you looking somewhere else?

**Comment by scottmwyant** [comment]
> I realized you're looking for a file within that zip file - it's in the hivemq-extension directory.

I didn't have the zip file. The docs have a relative path but it's was not clear to me how it should be resolved (relative to what exactly). I assumed it was trying to link to something in the repo, of course it doesn't make sense to have a .zip file in the repo but didn't have any other ideas.  

I see now that it's relative to the binary distribution available at https://sparkplug.eclipse.org/compatibility/get-listed/.

It's a simple thing really but I'm digging into this for the first time and didn't know. The web page links to GitHub but the User guide on GitHub doesn't link to the web page and there are no releases on GitHub either.
