### ISSUE TITLE
Question: yarn build fails

### ISSUE THREAD

**Issue by scottmwyant** [eclipse-sparkplug/sparkplug#484]
### What do you want to know?

Encountered this exception when running `yarn build`.

`Error: error:0308010C:digital envelope routines::unsupported`

Seems related to the version of node, using the `--openssl-legacy-provider` option.  Reference [stackoverflow.com/q/69692842](https://stackoverflow.com/q/69692842).

Just installed NodeJs `v18.17.1`.

![image](https://github.com/eclipse-sparkplug/sparkplug/assets/29161635/b29e41f8-b900-4b03-a5f3-52be80295c4c)

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by icraggs-sparkplug** [comment]
Thanks. I've seen that too, with the same resolution.

**Comment by scottmwyant** [comment]
For the uninitiated, you can set an environment variable option for Node.  Reference https://stackoverflow.com/a/69699772.
