### ISSUE TITLE
Consider/design Sparkplug modifications to better support Secondary Host Applications

### ISSUE THREAD

**Issue by wes-johnson** [eclipse-sparkplug/sparkplug#96]
This may involve using MQTT persistence or something else. But, Sparkplug requires a Rebirth request when a new host comes online. This is unnecessarily heavy and disruptive. We should consider how this can be better handled.

**Comment by matthewGEA** [comment]
@wes-johnson does #137 satisfy the intent here, or is there more to be discussed?

**Comment by wdougmiller** [comment]
> @wes-johnson does #137 satisfy the intent here, or is there more to be discussed?

Is this where a retained birth message comes into play?  Allowing a sparkplug aware broker to respond to rebirth requests?

**Comment by AlexGodbehere** [comment]
For what it's worth, we handle this using the concept of a `Directory` on the namespace: https://factoryplus.app.amrc.co.uk/docs/framework-components/core-components/directory

**Comment by wdougmiller** [comment]
> For what it's worth, we handle this using the concept of a `Directory` on the namespace: https://factoryplus.app.amrc.co.uk/docs/framework-components/core-components/directory

- @AlexGodbehere this is interesting. So, when a new host application subscribes to a topic, how does it know to get the information from the directory?

**Comment by AlexGodbehere** [comment]
> > For what it's worth, we handle this using the concept of a `Directory` on the namespace: https://factoryplus.app.amrc.co.uk/docs/framework-components/core-components/directory
> 
> * @AlexGodbehere this is interesting. So, when a new host application subscribes to a topic, how does it know to get the information from the directory?

In Factory+ the Directory is a well-known address where all others go to get information about all actors on the namespace. It's intrinsic to the framework, so it would be programmed into the application.

**Comment by wes-johnson** [comment]
This is now covered by this change: https://github.com/eclipse-sparkplug/sparkplug/pull/537/commits/9fe34c7c4cd3476ad3c45f72eaf9983f8ca36d7c

**Comment by wes-johnson** [comment]
This was created to potentially reduce load on the Sparkplug Edge Nodes: https://github.com/eclipse-sparkplug/sparkplug/issues/538
